### ISSUE TITLE
Pass in option for offset

### ISSUE THREAD

**Issue by inlikealion** [inlikealion/in-page-nav#2]
For certain use-cases it will be nice to pass-in an offset parameter for times the `.inview-navigator__nav` needs to stick below another fixed element (like a sticky header).

**Comment by jonathanrbowman** [comment]
Feature has been pushed to add support for this.

On the element with the `inview-navigator` class, just give it a `data-inview-navigator-offset="x"`, where `x` is an integer, and it will sticky, scroll to, and change nav state using that as an offset value. The offset currently only applies when on desktop, but if needed I could add a second option so you could also specify a mobile offset separately.

**Comment by inlikealion** [comment]
This looks good for now! Currently we don't have a need to offset on mobile, so this fixes the issue.
